### ISSUE TITLE
Search pertinency

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_api#519] opened 2016-11-22 14:36 UTC
If you serach "source petzl" on article ... you have 731 result vs 29 on v5 
I don't say I want to see only 29 ... but not 700 !

**Comment by asaunier** [comment] 2016-11-22 14:56
Perhaps a duplicate of https://github.com/c2corg/v6_api/issues/206 ?

**Comment by stef74** [comment] 2016-11-22 16:34
#397 is on demo ... so I complete the #206

**Comment by tsauerwein** [comment] 2016-11-22 16:48
Example added to https://github.com/c2corg/v6_api/issues/397

**Closed by tsauerwein** 2016-11-22 16:48 UTC
