### ISSUE TITLE
Geometry of associated waypoints

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_api#339] opened 2016-07-05 11:11 UTC
The client would like to see associated waypoints of a route on the map, but the geometry of associated wps is not returned. 

Haven't we discussed it and decided to not return it? (or i'm confusing sth)

> WP associated to the route should be displayed on the map.

**Comment by tsauerwein** [comment] 2016-07-05 15:47
Closing as a duplicate of https://github.com/c2corg/v6_api/issues/184

**Closed by tsauerwein** 2016-07-05 15:47 UTC
