### ISSUE TITLE
Clean non validated users

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_api#195] opened 2016-03-23 09:47 UTC
When a user is registered but the email is not validated in the delay, the user must be deleted.
See also https://github.com/c2corg/v6_api/pull/190#discussion_r57027022.

**Comment by tsauerwein** [comment] 2016-03-23 10:03
Or rather:

>  Maybe it would make sense to delay the creation of the user-profile until the account is confirmed. Otherwise un-confimed users might show up in the search and listings.

**Comment by asaunier** [comment] 2016-03-23 10:10
+1 with @tsauerwein proposal: no use creating the profile until the account is confirmed.

**Comment by asaunier** [comment] 2016-04-12 09:31
Closing since duplicate of https://github.com/c2corg/v6_api/issues/218

**Closed by asaunier** 2016-04-12 09:31 UTC
