### ISSUE TITLE
Outing's information: add associated photos attribute

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_api#684] opened 2017-08-23 07:20 UTC
Add an attribute for counting the number of photos associated to the outing. This number will be used by UI to display the number of photos in the outing's card.

**Comment by asaunier** [comment] 2017-09-06 11:44
Probably a duplicate of https://github.com/c2corg/v6_api/issues/338

**Comment by asaunier** [comment] 2017-09-06 12:03
It would make sense to extend this data to any document type, not only outings. It probably don't add extra work.

**Comment by asaunier** [comment] 2017-09-07 14:37
The issue about the ratings in the outings lists should probably be considered along with the current one. See https://github.com/c2corg/v6_api/issues/685

There are 2 main options:

## Option 1: "joins"

We add joins in the documents listing queries in order to also retrieve data from associated documents (a bit like the associated areas, already returned in the lists => TODO: investigate how the associated areas are managed in the doc lists), eg. number of associated images (nb of associated routes could be useful for WP lists, or nb of associated outings for routes lists?) or ratings of associated routes (for outings lists).

Pros:
* no change in the DB structure
* data are always up-to-date (cache?) even though new images are associated or removed

Cons:
* adds quite a lot of complexity to database queries?!
* impact on performances?

## Option 2 "stored metadata"

Metadata attribute are added to the documents table (but not to archived versions + no new version is created when the metadata are updated).

Pros:
* no additional complexity to code/queries when listing docs (only new attributes must be added to the list of "listing attributes", eg. https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_outing.py#L43)
* not much impact on performances

Cons:
* requires changes in the database structure, especially in the Document model https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/document.py#L70 (or in specific models for document type specific data such as outing ratings). TODO: make sure metadata are not lost when editing a document
* triggers must be set up in order to update the stored metadata when associated docs changes (eg. added or removed images, updated rating in an associated route)

**Comment by asaunier** [comment] 2017-09-07 15:14
Concerning option 1
> TODO: investigate how the associated areas are managed in the doc lists),

Joins are added here:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/document_listings.py#L103-L113

See also:
* https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/document_listings.py#L122-L123
* https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/document_listings.py#L189-L197
and
* https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/document.py#L154-L155
* https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/document.py#L178-L182

That's worth investigating this option 1 and eventually evaluate the impact on performances.

**Comment by Courgetteandratatouille** [comment] 2017-09-07 16:56
Where we can see the structure of the database ?

**Comment by asaunier** [comment] 2017-09-07 20:34
> Where we can see the structure of the database ?

There is no schema of the database. You have to look at the models here https://github.com/c2corg/v6_api/tree/master/c2corg_api/models

**Comment by Courgetteandratatouille** [comment] 2017-09-09 08:53
After a quick look, it's depend what the rating we want.
If we want a sort of merge of all rating for the route, the  option 2 is better. If we want to get  the associate route rating,  the option 1 is better. We must evaluate the impact on performances but i guess it will be ok.

**Comment by asaunier** [comment] 2017-09-11 15:46
How it was done in v5:
1. the list of outings is retrieved normally (with no route ratings) [1 DB request] https://github.com/c2corg/camptocamp.org/blob/master/apps/frontend/modules/outings/actions/actions.class.php#L618
1. associated images data are added using an additional tool (*) https://github.com/c2corg/camptocamp.org/blob/master/apps/frontend/modules/outings/actions/actions.class.php#L662
https://github.com/c2corg/camptocamp.org/blob/72e777075f2e6260b1d2ef563ab0f90c383038ba/lib/model/doctrine/Image.class.php#L951


(*) Images data are retrieved by
1. getting the list of ids of the associated images [1 DB request] 
https://github.com/c2corg/camptocamp.org/blob/72e777075f2e6260b1d2ef563ab0f90c383038ba/lib/model/doctrine/generated/BaseDocument.class.php#L2645
https://github.com/c2corg/camptocamp.org/blob/72e777075f2e6260b1d2ef563ab0f90c383038ba/lib/model/doctrine/Association.class.php#L815
1. data for the list of images ids retrieved above are then requested [1 DB request]: 
https://github.com/c2corg/camptocamp.org/blob/72e777075f2e6260b1d2ef563ab0f90c383038ba/lib/model/doctrine/generated/BaseDocument.class.php#L2715

Not sure then if/where an images count is performed.

**Comment by desnoes** [comment] 2017-09-11 16:36
> Not sure then if/where an images count is performed.

If my recollection is correct, in v5, there was no information about the number of images. There was only a picto indicating the presence of images.

**Comment by asaunier** [comment] 2017-09-12 14:49
Proposed pull request https://github.com/c2corg/v6_api/pull/689 uses none of the 2 options described above. It makes instead an additional DB query to get the numbers of associated images for the listed documents. A bit like in v5.

**Comment by fbunoz** [comment] 2017-09-19 15:02
> If my recollection is correct, in v5, there was no information about the number of images. There was only a picto indicating the presence of images.

There was the number of images. In doc lists, there was a dedicated column for this number. On the home, there was a picto, with the number in the tooltip.

> We must evaluate the impact on performances but i guess it will be ok.

On the V5, there was least and least OK...
But the V6 DB is different : there is a right copy of last doc version to generate the view table. On V5, there was a additional condition to extract the last versions from the versions table.

The proposed solution is enough for now, but in few years we'll have to improve performances (there are 150k new images per year).

**Closed** 2017-09-29 05:22 UTC
Labels: ready for testing, SA
