### ISSUE TITLE
Auto simplify received route geometries?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#359] opened 2016-08-09 14:36 UTC
Some route geometries have a bunch of points and are really big.

For instance:
http://www.camptocamp.org/routes/211687/fr/mont-de-grange-traversee-bel-air-coicon
http://c2corgv6.demo-camptocamp.com/routes/211687/fr
The GPX file available on v5 is > 800 kB!

That's a problem because the route detail view page is too big. We could also have problems in the WP page is the associated routes tracks are shown as well (see https://github.com/c2corg/v6_api/pull/358)

**Comment by tsauerwein** [comment] 2016-08-09 14:37
See also https://github.com/c2corg/v6_api/issues/94

**Comment by tsauerwein** [comment] 2016-11-23 14:57
Duplicate of https://github.com/c2corg/v6_api/issues/529

**Closed by tsauerwein** 2016-11-23 14:57 UTC
