### ISSUE TITLE
Preferred areas filters are too restrictive in the feed

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#621] opened 2017-02-03 14:37 UTC
If a user has areas in their filtering preferences, all non-geometric documents (eg. articles or books) are stripped out of the feed.

Area-related filtering should only be performed on feed item with a geometry.

**Comment by tsauerwein** [comment] 2017-02-07 15:55
Duplicate of https://github.com/c2corg/v6_api/issues/510?

**Closed** 2017-02-07 17:45 UTC
Labels: Home Page / activity feed
