### ISSUE TITLE
Error while saving an outing

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#303] opened 2016-06-03 16:12 UTC
(Not sure yet the problem occurs systematically)

I have edited one of my existing outings (http://localhost:6555/outings/edit/734063/fr) and added a new route (http://localhost:6555/routes/45168/fr => Mont de Grange couloir de Pertuis).

The API fails with the following SQLAlchemy error:

> File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_debugtoolbar/panels/performance.py&#34;, line 57, in resource_timer_handler
    result = handler(request)
  File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py&#34;, line 48, in excview_tween
    request_iface=request_iface.combined
  File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/view.py&#34;, line 541, in _call_view
    response = view_callable(context, request)
  File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py&#34;, line 286, in _authdebug_view
    return view(context, request)
  File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py&#34;, line 385, in viewresult_to_response
    result = view(context, request)
  File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py&#34;, line 20, in excview_tween
    response = handler(request)
  File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_tm/__init__.py&#34;, line 101, in tm_tween
    reraise(*exc_info)
  File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_tm/compat.py&#34;, line 15, in reraise
    raise value
  File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_tm/__init__.py&#34;, line 83, in tm_tween
    response = handler(request)
  File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/router.py&#34;, line 145, in handle_request
    view_name
  File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/view.py&#34;, line 541, in _call_view
    response = view_callable(context, request)
  File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py&#34;, line 602, in __call__
    return view(context, request)
  File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py&#34;, line 328, in attr_view
    return view(context, request)
  File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py&#34;, line 304, in predicate_wrapper
    return view(context, request)
  File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py&#34;, line 286, in _authdebug_view
    return view(context, request)
  File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py&#34;, line 244, in _secured_view
    return view(context, request)
  File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py&#34;, line 353, in rendered_view
    result = view(context, request)
  File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py&#34;, line 507, in _requestonly_view
    response = view(request)
  File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/cornice/service.py&#34;, line 571, in wrapper
    response = view_()
  File &#34;/home/alex/v6_api/c2corg_api/views/outing.py&#34;, line 142, in put
    Outing, schema_outing, before_update=update_default_geometry)
  File &#34;/home/alex/v6_api/c2corg_api/views/document.py&#34;, line 295, in _put
    update_types,  changed_langs)
  File &#34;/home/alex/v6_api/c2corg_api/views/document.py&#34;, line 399, in _update_version
    archive = self._get_document_archive(document, update_types)
  File &#34;/home/alex/v6_api/c2corg_api/views/document.py&#34;, line 435, in _get_document_archive
    one()
  File &#34;/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/orm/query.py&#34;, line 2702, in one
    &#34;Multiple rows were found for one()&#34;)
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one()

**Comment by asaunier** [comment] 2016-06-03 16:27
Mmm I have a similar error while editing a route.
I see nothing special in the request.

But it worked for some other cases/document. I have not figure out how to reproduce the problem yet.

**Comment by tsauerwein** [comment] 2016-06-06 06:44
For some reasons there are two entries in `documents_archives` with the same version for document 734063 (`select document_id, id, version from guidebook.documents_archives where document_id = 734063;`).

The document seems to be migrated correctly from v5. Do you remember what you did with this outing, so that I could try to reproduce?

**Comment by tsauerwein** [comment] 2016-06-06 09:53
With https://github.com/c2corg/v6_api/pull/304 I added constraints, so that no two entries with the same version for a document can be created. This will help find the problem that created the situation you've encountered.

**Comment by asaunier** [comment] 2016-06-07 07:22
> Do you remember what you did with this outing, so that I could try to reproduce?

Unfortunately I don't remember.

> With #304 I added constraints, so that no two entries with the same version for a document can be created. This will help find the problem that created the situation you've encountered.

OK thanks

**Comment by tsauerwein** [comment] 2016-06-15 07:49
I understood what was going wrong. The migration script created multiple entries in `document_locales_archives` for a document id and locale with the same version. This (correctly) caused an error. The migration script will be fixed in #322.

**Comment by asaunier** [comment] 2016-06-22 08:55
I wonder if this issue is really fixed: my API and DB are up-to-date on the dev server (data migrated from scratch yesterday) but I have just encounter an integrity error while trying to edit a waypoint:

Request URL:http://c2corgv6-demo.gis.internal:6545/waypoints/37414
Request Method:PUT
Request Payload:
> {"message":"","document":{"geometry":{"version":1,"geom":"{\"type\":\"Point\",\"coordinates\":[794547.4296361126,5864172.342360474]}"},"prominence":null,"maps_info":null,"quality":"medium","waypoint_type":"summit","type":"w","maps":[{"locales":[{"title":"Col du Pillon","version":1,"lang":"fr"}],"code":"41","version":1,"available_langs":null,"document_id":104626,"protected":false,"type":"m","editor":"Swisstopo"},{"locales":[{"title":"Rochers de Naye","version":1,"lang":"fr"}],"code":"262","version":1,"available_langs":null,"document_id":104700,"protected":false,"type":"m","editor":"Swisstopo"},{"locales":[{"title":"Château-d'Oex","version":1,"lang":"fr"}],"code":"1245","version":1,"available_langs":null,"document_id":104881,"protected":false,"type":"m","editor":"Swisstopo"}],"locales":[{"description":null,"title":"Vanil de l'Ecri","version":1,"summary":null,"lang":"fr"}],"version":2,"document_id":37414,"elevation":2376,"protected":false,"associations":{"waypoint_children":[],"waypoints":[]}}}

Response: a 500 error with message
> sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "uq_documents_geometries_archives_document_id_version_lang"
DETAIL:  Key (version, document_id)=(2, 37414) already exists.
 [SQL: 'INSERT INTO guidebook.documents_geometries_archives (version, document_id, geom_detail, geom) VALUES (%(version)s, %(document_id)s, ST_GeomFromEWKT(%(geom_detail)s), ST_GeomFromWKB(%(ST_GeomFromWKB_1)s, %(ST_GeomFromWKB_2)s)) RETURNING guidebook.documents_geometries_archives.id'] [parameters: {'document_id': 37414, 'geom_detail': None, 'ST_GeomFromWKB_1': &lt;memory at 0x7f80633f1750&gt;, 'ST_GeomFromWKB_2': 3857, 'version': 2}]

**Comment by tsauerwein** [comment] 2016-06-23 15:58
Yes, you are right. There still was a problem with the geometries. This is fixed in #328.

**Closed** 2016-06-24 08:47 UTC
